name: Build

on:
  workflow_dispatch:
    inputs:
      package_name:
        description: 'Package name of the game:'
        required: true
        default: 'com.mobile.legends'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Prepare and Build Module
        run: |
          chmod +x ./gradlew
          sed -i "s/com.game.packagename/${{ github.event.inputs.package_name }}/g" module/src/main/cpp/game.h
          sed -i 's/moduleDescription = "/moduleDescription = "(${{ github.event.inputs.package_name }}) /g' module.gradle
          ./gradlew build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4   # ‚Üê This was v3, now fixed to v4
        with:
          name: zygisk-il2cppdumper-${{ github.event.inputs.package_name }}
          path: app/build/outputs/apk/release/app-release.apk
